### ISSUE TITLE
Wrong description in "Stress" example

### ISSUE THREAD

**Issue by Sec-ant** [wbkd/react-flow-docs#4]
https://github.com/wbkd/react-flow-docs/blob/main/docs/examples/stress.mdx

The description is mistakenly from the "Save and Restore" example.

PS: Same issue in "Smooth Transition".

**Comment by terceser** [comment]
Same issue in Drag Handle example

https://github.com/wbkd/react-flow-docs/blob/main/docs/examples/drag-handle.mdx

**Comment by moklick** [comment]
thanks!
